Change LogGroup and added possibility to reload user database

diff --git a/templates/03-openldap.yaml b/templates/03-openldap.yaml
--- a/templates/03-openldap.yaml
+++ b/templates/03-openldap.yaml
@@ -65,8 +65,9 @@ Parameters:
     NoEcho: true
     MinLength: 3
   LDAPUsersLdif: 
-    Description: 'The LDAP initial User database'
+    Description: 'The LDAP initial User database. Should be an S3 url containing an LDIF database with the same RootDC as above'
     Type: String
+    Default: 's3://mybucketname/import.ldif'
 Mappings:
   # cf 01-mappings.yaml
   RegionMap:
@@ -117,7 +118,7 @@ Resources:
       HealthCheckType: ELB
       LaunchConfigurationName: !Ref LaunchConfiguration
       MinSize: 1
-      MaxSize: 1
+      MaxSize: 2
       NotificationConfigurations:
         - TopicARN: !Ref TopicHealth
           NotificationTypes:
@@ -189,18 +190,17 @@ Resources:
       LoadBalancerArn: !Ref LoadBalancer
       Port: 389
       Protocol: TCP
-  HostLogs:
+  LogGroup:
     Type: 'AWS::Logs::LogGroup'
     Properties:
-      LogGroupName:
-        'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
+      LogGroupName: !Sub '${AWS::StackName}'
       RetentionInDays: 7
   LaunchConfiguration:
     Type: 'AWS::AutoScaling::LaunchConfiguration'
     Metadata:
       AWS::CloudFormation::Init:
         configSets: 
-          default: [ Bootstrap, InstallOpenLDAP ]
+          default: [ Bootstrap, InstallApplication ]
         Bootstrap:
           packages:
             yum:
@@ -225,45 +225,45 @@ Resources:
                 datetime_format = %b %d %H:%M:%S
                 file = /var/log/messages
                 log_stream_name = {instance_id}/var/log/messages
-                log_group_name = ${HostLogs}
+                log_group_name = ${LogGroup}
                 [/var/log/secure]
                 datetime_format = %b %d %H:%M:%S
                 file = /var/log/secure
                 log_stream_name = {instance_id}/var/log/secure
-                log_group_name = ${HostLogs}
+                log_group_name = ${LogGroup}
                 [/var/log/cron]
                 datetime_format = %b %d %H:%M:%S
                 file = /var/log/cron
                 log_stream_name = {instance_id}/var/log/cron
-                log_group_name = ${HostLogs}
+                log_group_name = ${LogGroup}
                 [/var/log/cloud-init.log]
                 datetime_format = %b %d %H:%M:%S
                 file = /var/log/cloud-init.log
                 log_stream_name = {instance_id}/var/log/cloud-init.log
-                log_group_name = ${HostLogs}
+                log_group_name = ${LogGroup}
                 [/var/log/cfn-init.log]
                 datetime_format = %Y-%m-%d %H:%M:%S
                 file = /var/log/cfn-init.log
                 log_stream_name = {instance_id}/var/log/cfn-init.log
-                log_group_name = ${HostLogs}
+                log_group_name = ${LogGroup}
                 [/var/log/cfn-hup.log]
                 datetime_format = %Y-%m-%d %H:%M:%S
                 file = /var/log/cfn-hup.log
                 log_stream_name = {instance_id}/var/log/cfn-hup.log
-                log_group_name = ${HostLogs}
+                log_group_name = ${LogGroup}
                 [/var/log/cfn-init-cmd.log]
                 datetime_format = %Y-%m-%d %H:%M:%S
                 file = /var/log/cfn-init-cmd.log
                 log_stream_name = {instance_id}/var/log/cfn-init-cmd.log
-                log_group_name = ${HostLogs}
+                log_group_name = ${LogGroup}
                 [/var/log/cloud-init-output.log]
                 file = /var/log/cloud-init-output.log
                 log_stream_name = {instance_id}/var/log/cloud-init-output.log
-                log_group_name = ${HostLogs}
+                log_group_name = ${LogGroup}
                 [/var/log/dmesg]
                 file = /var/log/dmesg
                 log_stream_name = {instance_id}/var/log/dmesg
-                log_group_name = ${HostLogs}
+                log_group_name = ${LogGroup}
               mode: '000644'
               owner: root
               group: root
@@ -340,13 +340,37 @@ Resources:
                 files:
                   - /etc/yum/yum-cron.conf
                   - /etc/yum/yum-cron-hourly.conf
-        InstallOpenLDAP:
+        InstallApplication:
           packages:
             yum:
               openldap: []
               openldap-clients: []
               openldap-servers: []
           files:
+            '/etc/crontab':
+              content: !Sub |
+                SHELL=/bin/bash
+                PATH=/sbin:/bin:/usr/sbin:/usr/bin
+                MAILTO=root
+                HOME=/
+                * * * * * root /root/update_users.sh ${LDAPUsersLdif}
+              mode: '000744'
+              owner: 'root'
+              group: 'root'
+            '/root/update_users.sh':
+              content: !Sub |
+                #!/bin/bash
+                ldapUsersLdif="$1"
+                [ -z "$ldapUsersLdif" ] && echo "Invalid ldapUsersLdif" && exit 1
+                echo "Loading initial LDIF user database from $ldapUsersLdif"
+                aws s3 cp "$ldapUsersLdif" /root/import.ldif
+                ldapsearch -x -LLL -D "cn=Manager,${RootDC}" -w "${ManagerPassword}" -H ldapi:/// -b "${RootDC}" 2> /dev/null | \
+                  awk -F": " '$1~/^\s*dn/{print $2}' > /root/to_delete.txt
+                [ -s to_delete.txt ] && ldapdelete -r -D "cn=Manager,${RootDC}" -w "${ManagerPassword}" -H ldapi:/// -f /root/to_delete.txt
+                ldapadd -x -D "cn=Manager,${RootDC}" -w "${ManagerPassword}" -H ldapi:/// -f /root/import.ldif
+              mode: '000700'
+              owner: 'root'
+              group: 'root'
             '/root/configure_ldap.sh':
               content: !Sub |
                 #!/bin/bash
@@ -377,24 +401,7 @@ Resources:
                 add: olcRootPW
                 olcRootPW: $managerPassword
                 EOF
-                # TODO: explain
-                # 
-                domainComponent=$(echo -n "$rootDC"|cut -d',' -f1|cut -d'=' -f2)
-                
-                echo "Adding '$rootDC' (w/ dc=$domainComponent)..."
-                ldapadd -x -D "cn=Manager,$rootDC" -w "$managerPassword" -H ldapi:/// <<EOF
-                dn: $rootDC
-                dc: $domainComponent
-                o: LDAP Server
-                description: Root entry for LDAP Server
-                objectClass: top
-                objectclass: dcObject
-                objectclass: organization
-                EOF
-                if [ ! -z "${LDAPUsersLdif}" ]; then
-                  echo "Loading initial LDIF user database"
-                  ldapadd -x -D "cn=Manager,$rootDC" -w "$managerPassword" -H ldapi:/// -f ${LDAPUsersLdif}
-                fi
+                [ ! -z "${LDAPUsersLdif}" ] && /root/update_users.sh ${LDAPUsersLdif}
               mode: '000744'
               owner: 'root'
               group: 'root'
