Adding AWS inspector stack Fixed LDAP configuration for Jenkins

diff --git a/templates/06-gitlab.yaml b/templates/06-gitlab.yaml
--- a/templates/06-gitlab.yaml
+++ b/templates/06-gitlab.yaml
@@ -235,6 +235,7 @@ Resources:
         BootstrapGitlab:
           packages:
             yum: 
+              jq: []
               postfix: []
               policycoreutils-python: []
           files: 
@@ -293,30 +294,19 @@ Resources:
                     'user_filter' => '(objectclass=person)'
                   }
                 }
-            '/root/gitlab_change_password.sh':
-              content: |
-                #!/bin/bash
-                email=$1
-                password=$2
-                [ -z "$email" ] && echo "Invalid email" && exit 1
-                [ -z "$password" ] && echo "Invalid password" && exit 1
-                gitlab-rake gitlab:setup GITLAB_ROOT_PASSWORD="$password" GITLAB_ROOT_EMAIL="$email" < <(echo yes) > /dev/null 2>&1
-                echo "Changed password for user root"
-              mode: '000700'
-              owner: 'root'
-              group: 'root'
             '/root/gitlab_configure_url.sh':
               content: |
                 #!/bin/bash -x
                 external_url="$1"
                 [ -z "$external_url" ] && echo "Invalid external_url" && exit 1
+                external_url=${external_url,,}
                 sed -ibckp -E "s/%external_url%/$external_url/" /etc/gitlab/gitlab.rb
               mode: '000700'
               owner: 'root'
               group: 'root'
             '/root/gitlab_configure_ldap.sh':
               content: |
-                #!/bin/bash -x
+                #!/bin/bash
                 ldapHostname=$1
                 ldapPort=$2
                 rootDC=$3
@@ -331,25 +321,40 @@ Resources:
               mode: '000700'
               owner: 'root'
               group: 'root'
-            '/root/other_valuable_settings.json':
+            '/root/gitlab_change_password.sh':
               content: |
-                { 
-                  "default_project_visibility": "public",
-                  "email_author_in_body": true,
-                  "gravatar_enabled": false,
-                  "help_page_hide_commercial_content": true,
-                  "html_emails_enabled": true,
-                  "import_sources": [],
-                  "password_authentication_enabled_for_git": false,
-                  "repository_checks_enabled": true,
-                  "restricted_visibility_levels" : [ "private", "internal" ],
-                  "signup_enabled": false,
-                  
-                }
+                #!/bin/bash
+                email=$1
+                password=$2
+                [ -z "$email" ] && echo "Invalid email" && exit 1
+                [ -z "$password" ] && echo "Invalid password" && exit 1
+                gitlab-rake gitlab:setup GITLAB_ROOT_PASSWORD="$password" GITLAB_ROOT_EMAIL="$email" < <(echo yes) > /dev/null 2>&1
+                echo "Changed password for user root"
               mode: '000700'
               owner: 'root'
               group: 'root'
-              
+            '/root/gitlab_extra_config.sh':
+              content: |
+                #!/bin/bash
+                email=$1
+                password=$2
+                [ -z "$email" ] && echo "Invalid email" && exit 1
+                [ -z "$password" ] && echo "Invalid password" && exit 1
+                # Obtain a token
+                token=$(curl -s -F grant_type=password -F "username=$email" -F "password=$password" -X POST http://localhost:80/oauth/token | jq '.access_token' | tr -d '"')
+                url="http://localhost:80/api/v4/application/settings"
+                echo "Changing settings (token=$token)..."
+                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?signup_enabled=false" > /dev/null
+                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?default_project_visibility=public" > /dev/null
+                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?email_author_in_body=true" > /dev/null
+                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?gravatar_enabled=false" > /dev/null
+                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?help_page_hide_commercial_content=true" > /dev/null
+                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?html_emails_enabled=true" > /dev/null
+                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?html_emails_enabled=true" > /dev/null
+                curl -s --request POST -H "Authorization: Bearer $token" -F token=$token http://localhost:80/oauth/revoke > /dev/null
+              mode: '000700'
+              owner: 'root'
+              group: 'root'
           commands:
             '01_gitlab_configure_url':
               command: !Sub 'sudo /root/gitlab_configure_url.sh ${LoadBalancerGitlab.DNSName}'
@@ -366,6 +371,8 @@ Resources:
               command: 'sudo gitlab-ctl reconfigure'
             '04_gitlab_change_password':
               command: !Sub 'sudo /root/gitlab_change_password.sh "${GitlabAdminEmail}" "${GitlabAdminPassword}"'
+            '05_gitlab_extra_config':
+              command: !Sub 'sudo /root/gitlab_extra_config.sh "${GitlabAdminEmail}" "${GitlabAdminPassword}"'
     Properties: 
       DisableApiTermination: false
       InstanceInitiatedShutdownBehavior: stop
diff --git a/templates/08-jenkins.yaml b/templates/08-jenkins.yaml
--- a/templates/08-jenkins.yaml
+++ b/templates/08-jenkins.yaml
@@ -28,6 +28,7 @@ Metadata:
       Parameters:
       - ParentVpcStack
       - ParentLDAPStack
+      - ParentArtifactoryStack
     - Label: 
         default: 'EC2 Parameters'
       Parameters:
@@ -40,6 +41,7 @@ Metadata:
     - Label:
         default: 'Jenkins Parameters'
       Parameters:
+      - JenkinsAdminEmail
       - JenkinsAdminPassword
 Parameters: 
   ParentVpcStack: 
@@ -48,10 +50,15 @@ Parameters:
     MinLength: 1
     ConstraintDescription: 'must be the name of the VPC stack'
   ParentLDAPStack:
-    Description: "Enter the name of the OpenLDAP Stack"
+    Description: "Enter the name of the LDAP Stack"
     Type: String
     MinLength: 1
     ConstraintDescription: 'must be the name of the LDAP stack'
+  ParentArtifactoryStack:
+    Description: "Enter the name of the Artifactory Stack"
+    Type: String
+    MinLength: 1
+    ConstraintDescription: 'must be the name of the Artifactory stack'
   KeyName: 
     Description: "The Jenkins instance Key Pair"
     Type: "AWS::EC2::KeyPair::KeyName"
@@ -65,6 +72,10 @@ Parameters:
     Type: String
     NoEcho: true
     MinLength: 3
+  JenkinsAdminEmail: 
+    Description: 'The Jenkins Admin email'
+    Type: String
+    Default: ''
   JenkinsAdminPassword: 
     Description: 'The Jenkins Admin password'
     Type: String
@@ -235,7 +246,13 @@ Resources:
             yum: 
               py-bcrypt: []
               java-1.8.0-openjdk: []
+              java-1.8.0-openjdk-devel: []
           files: 
+            '/etc/yum.repos.d/epel-apache-maven.repo':
+              source: 'http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo'
+              mode: "000644"
+              owner: "root"
+              group: "root"
             '/etc/yum.repos.d/jenkins.repo':
               source: 'http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo'
               mode: "000644"
@@ -249,8 +266,15 @@ Resources:
                 [ ! -d $MNT ] && mkdir $MNT
                 mount /dev/xvdb $MNT
                 echo "/dev/xvdb $MNT ext4 defaults,nofail 0 2" > /etc/fstab
-                [ ! -d $MNT/opt ] && mkdir $MNT/opt
-                [ ! -d /opt     ] && mkdir -p /opt; ln -s $MNT/opt /opt/jenkins
+                [ ! -d $MNT/var ] && mkdir $MNT/var
+                [ ! -d /var/lib ] && mkdir -p /var/lib; ln -s $MNT/var /var/lib/jenkins
+              mode: "000700"
+              owner: "root"
+              group: "root"
+            '/root/fix_repo.sh': 
+              content: |
+                #!/bin/bash -x
+                sed -i s/\$releasever/7/g /etc/yum.repos.d/epel-apache-maven.repo
               mode: "000700"
               owner: "root"
               group: "root"
@@ -263,39 +287,190 @@ Resources:
               command: 'sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key'
             '04_create_fs':
               command: 'sudo /root/create_fs.sh'              
+            '05_fix_repo':
+              command: 'sudo /root/fix_repo.sh'              
         InstallJenkins: 
           packages:
             yum:
+              ant: []
+              git: []
               jenkins: []
+              apache-maven: []
           files:
-            '/root/ldap_config.xml':
+            '/var/lib/jenkins/hudson.tasks.Ant.xml':
               content: |
-                <securityRealm class="hudson.security.LDAPSecurityRealm" plugin="ldap@1.20">
-                  <disableMailAddressResolver>false</disableMailAddressResolver>
-                  <configurations>
-                    <jenkins.security.plugins.ldap.LDAPConfiguration>
-                      <server>%ldapHostname%:%ldapPort%</server>
-                      <rootDN>%rootDC%</rootDN>
-                      <inhibitInferRootDN>false</inhibitInferRootDN>
-                      <userSearchBase>ou=People</userSearchBase>
-                      <userSearch>(&amp;(objectClass=person)(uid={0}))</userSearch>
-                      <groupMembershipStrategy class="jenkins.security.plugins.ldap.FromGroupSearchLDAPGroupMembershipStrategy">
-                      <filter></filter>
-                      </groupMembershipStrategy>
-                      <managerDN>%managerDN%</managerDN>
-                      <managerPasswordSecret>%managerPassword%</managerPasswordSecret>
-                      <displayNameAttributeName>displayName</displayNameAttributeName>
-                      <mailAddressAttributeName>mail</mailAddressAttributeName>
-                      <ignoreIfUnavailable>false</ignoreIfUnavailable>
-                      <extraEnvVars class="linked-hash-map">
-                        <entry><string></string><string></string></entry>
-                      </extraEnvVars>
-                    </jenkins.security.plugins.ldap.LDAPConfiguration>
-                  </configurations>
-                  <userIdStrategy class="jenkins.model.IdStrategy$CaseInsensitive"/>
-                  <groupIdStrategy class="jenkins.model.IdStrategy$CaseInsensitive"/>
-                  <disableRolePrefixing>true</disableRolePrefixing>
-                </securityRealm>
+                <?xml version='1.1' encoding='UTF-8'?>
+                <hudson.tasks.Ant_-DescriptorImpl>
+                  <installations><hudson.tasks.Ant_-AntInstallation><name>ant</name><home>/usr/share/ant</home><properties/></hudson.tasks.Ant_-AntInstallation></installations>
+                </hudson.tasks.Ant_-DescriptorImpl>
+              mode: '000644'
+              owner: 'jenkins'
+              group: 'jenkins'
+            '/var/lib/jenkins/hudson.tasks.Maven.xml':
+              content: |
+                <?xml version='1.1' encoding='UTF-8'?>
+                <hudson.tasks.Maven_-DescriptorImpl>
+                  <installations><hudson.tasks.Maven_-MavenInstallation><name>maven</name><home>/usr/share/apache-maven</home><properties/></hudson.tasks.Maven_-MavenInstallation></installations>
+                </hudson.tasks.Maven_-DescriptorImpl>
+              mode: '000644'
+              owner: 'jenkins'
+              group: 'jenkins'
+            '/var/lib/jenkins/hudson.plugins.git.GitTool.xml':
+              content: |
+                <?xml version='1.1' encoding='UTF-8'?>
+                <hudson.plugins.git.GitTool_-DescriptorImpl>
+                  <installations class="hudson.plugins.git.GitTool-array"><hudson.plugins.git.GitTool><name>Default</name><home>/usr/bin/git</home><properties/></hudson.plugins.git.GitTool></installations>
+                </hudson.plugins.git.GitTool_-DescriptorImpl>
+              mode: '000644'
+              owner: 'jenkins'
+              group: 'jenkins'
+            '/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml': 
+              content: !Sub |
+                <?xml version='1.1' encoding='UTF-8'?>
+                <jenkins.model.JenkinsLocationConfiguration>
+                  <adminAddress>${JenkinsAdminEmail}</adminAddress>
+                  <jenkinsUrl>http://${LoadBalancerJenkins.DNSName}/</jenkinsUrl>
+                </jenkins.model.JenkinsLocationConfiguration>
+              mode: '000644'
+              owner: 'jenkins'
+              group: 'jenkins'
+            '/root/jenkins_configure_ldap.groovy':
+              content: |
+                // Inspired from https://github.com/samrocketman/jenkins-bootstrap-shared
+                import hudson.security.LDAPSecurityRealm
+                import hudson.util.Secret
+                import jenkins.model.Jenkins
+                import jenkins.model.IdStrategy
+                import jenkins.security.plugins.ldap.LDAPConfiguration
+
+                if(!(Jenkins.instance.securityRealm instanceof LDAPSecurityRealm)) {
+                  LDAPConfiguration conf = new LDAPConfiguration(
+                    '%ldapHost%:%ldapPort%',
+                    '%rootDC%',
+                    false,
+                    '%managerDN%',
+                    Secret.fromString('%managerPassword%'))
+                  conf.userSearchBase = 'ou=People'
+                  conf.userSearch = 'uid={0}'
+                  conf.groupSearchBase = 'ou=Group'
+                  conf.displayNameAttributeName = 'displayName'
+                  conf.mailAddressAttributeName = 'mail'
+                  List<LDAPConfiguration> configurations = [conf]
+                  Jenkins.instance.securityRealm = new LDAPSecurityRealm(
+                    configurations,
+                    false,
+                    null,
+                    IdStrategy.CASE_INSENSITIVE,
+                    IdStrategy.CASE_INSENSITIVE)
+                  Jenkins.instance.save()
+                  println 'Security realm set to LDAP.'
+                } else {
+                  println 'Nothing changed.  LDAP security realm already configured.'
+                }
+              mode: '000600'
+              owner: 'root'
+              group: 'root'
+            '/root/jenkins_configure_ldap.sh':
+              content: |
+                #!/bin/bash
+                ldapHostname=$1
+                ldapPort=$2
+                rootDC=$3
+                managerDN="$4"
+                managerPassword=$5
+                [ -z "$ldapHostname" ] && echo "Invalid ldapHostname" && exit 1
+                [ -z "$ldapPort" ] && echo "Invalid ldapPort" && exit 1
+                [ -z "$rootDC" ] && echo "Invalid rootDC" && exit 1
+                [ -z "$managerDN" ] && echo "Invalid managerDN" && exit 1
+                [ -z "$managerPassword" ] && echo "Invalid managerPassword" && exit 1
+                [ -z "$adminPassword" ] && echo "Invalid adminPassword" && exit 1
+                sed -ibckp -E "s/%ldapHostname%/$ldapHostname/;s/%ldapPort%/$ldapPort/;s/%rootDC%/$rootDC/;s/%managerDN%/$managerDN/;s/%managerPassword%/$managerPassword/" /root/jenkins_configure_ldap.groovy
+                echo "Configuring LDAP..."
+                initialPassword=/var/lib/jenkins/secrets/initialAdminPassword
+                cli=/var/cache/jenkins/war/WEB-INF/jenkins-cli.jar
+                url=http://localhost:8080
+                java -jar $cli -s $url -auth "admin:$(cat $initialPassword)" groovy = --username admin --password $(cat $initialPassword) < <(cat /root/configure_ldap.groovy)
+              mode: '000700'
+              owner: 'root'
+              group: 'root'
+            '/root/plugins.txt':
+              content: |
+                ace-editor
+                ant
+                antisamy-markup-formatter
+                artifactory
+                build-pipeline-plugin
+                build-timeout
+                checkstyle
+                categorized-view 
+                cloudbees-folder
+                cobertura
+                compact-columns 
+                conditional-buildstep
+                config-file-provider
+                configure-job-column-plugin 
+                copyartifact
+                downstream-buildview 
+                email-ext
+                emailext-template
+                embeddable-build-status
+                envinject 
+                extensible-choice-parameter 
+                git-parameter
+                gradle
+                greenballs 
+                groovy 
+                groovy-postbuild 
+                htmlpublisher
+                javadoc 
+                jira 
+                job-dsl 
+                jenkins-multijob-plugin
+                junit
+                ldap
+                mailer
+                matrix-auth
+                parameterized-trigger
+                pipeline-stage-view
+                publish-over-ssh
+                rebuild
+                sonar
+                ssh
+                ssh-agent
+                ssh-slaves
+                swarm 
+                timestamper
+                token-macro 
+                view-job-filters 
+                warnings
+                workflow-aggregator
+                ws-cleanup
+              mode: '000700'
+              owner: 'root'
+              group: 'root'
+            '/root/jenkins_configure.sh': 
+              content: |
+                #!/bin/bash
+                initialPassword=/var/lib/jenkins/secrets/initialAdminPassword
+                cli=/var/cache/jenkins/war/WEB-INF/jenkins-cli.jar
+                url=http://localhost:8080
+                wait() {
+                  # make sure that I re-read the initial password each time...
+                  until $(curl -s --max-time 60 -o /dev/null --head --fail --user "admin:$(cat $initialPassword 2> /dev/null)" $url/cli/); do
+                    echo -n '.'; sleep 1
+                  done
+                }
+                echo -n "Waiting for Jenkins to startup..."
+                wait
+                echo ""
+                echo "Configuring slaveAgentPort..."
+                sed -i -e "s@<slaveAgentPort>.*</slaveAgentPort>@<slaveAgentPort>49817</slaveAgentPort>@" /var/lib/jenkins/config.xml
+                echo "Configuring label..."
+                sed -i -e "s@<label>.*</label>@<label>master</label>@" /var/lib/jenkins/config.xml
+                service jenkins restart
+                wait
+                echo "Installing plugins..."
+                java -jar $cli -s $url -auth "admin:$(cat $initialPassword)" install-plugin $(cat /root/plugins.txt | tr "\n" " ")
               mode: '000700'
               owner: 'root'
               group: 'root'
@@ -303,37 +478,33 @@ Resources:
               content: |
                 #!/bin/bash
                 password=$1
-                [ -z "$password" ] && echo "Invalid password" && exit
-                bcrypt_password=$(python2.6 -c "import bcrypt; print(bcrypt.hashpw('$password', bcrypt.gensalt(log_rounds=10)))")
-                while [ ! -f /var/lib/jenkins/users/admin/config.xml ]; do
-                  echo -n '.'
-                  sleep 1
-                done
-                sed -ibckp "s-<passwordHash>.*</passwordHash>-<passwordHash>#jbcrypt:$bcrypt_password</passwordHash>-" /var/lib/jenkins/users/admin/config.xml
-              mode: '000700'
-              owner: 'root'
-              group: 'root'
-            '/root/jenkins_configure_ldap.sh': 
-              content: |
-                #!/bin/bash
-                # LOOK AT https://jenkins.io/doc/book/managing/cli/
-                echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("user1", "password123")' | \
-                  java -jar jenkins-cli.jar -s "http://localhost:8080/" -noKeyAuth groovy = --username admin --password xxx 
-              mode: '000700'
-              owner: 'root'
-              group: 'root'              
+                [ -z "$password" ] && echo "Invalid password" && exit 1
+                initialPassword=/var/lib/jenkins/secrets/initialAdminPassword
+                cli=/var/cache/jenkins/war/WEB-INF/jenkins-cli.jar
+                url=http://localhost:8080
+                echo "Changing default password for admin..."
+                echo "jenkins.model.Jenkins.instance.securityRealm.createAccount('admin', '$password')" | \
+                  java -jar $cli -s $url -auth "admin:$(cat $initialPassword)" groovy =
           commands:
             '01_alternatives_java':
               command: 'sudo /usr/sbin/alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java'
             '02_jenkins_start':
               command: 'sudo service jenkins start'
-            '03_jenkins_change_password':
+            '03_jenkins_configure':
+              command: 'sudo /root/jenkins_configure.sh'
+            '04_jenkins_configure_ldap':
+              command: !Join
+                - ' '
+                - - 'sudo /root/jenkins_configure_ldap.sh'
+                  - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-LDAPHostname'
+                  - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-LDAPPort'
+                  - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-RootDC'
+                  - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-ManagerDN'
+            '05_jenkins_change_password':
               command: !Join
                 - ' '
                 - - 'sudo /root/jenkins_change_password.sh'
                   - !Sub '${JenkinsAdminPassword}'
-            '04_install_plugins':
-              command: !Sub 'java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s "http://localhost:8080/" -auth "admin:${JenkinsAdminPassword}" install-plugin $(cat /root/plugins.txt | tr "\n" " ")'
             '05_jenkins_restart':
               command: 'sudo service jenkins restart'
           services: 
