Fixed GITLAB installation

diff --git a/templates/06-gitlab.yaml b/templates/06-gitlab.yaml
--- a/templates/06-gitlab.yaml
+++ b/templates/06-gitlab.yaml
@@ -328,37 +328,43 @@ Resources:
                 password=$2
                 [ -z "$email" ] && echo "Invalid email" && exit 1
                 [ -z "$password" ] && echo "Invalid password" && exit 1
-                gitlab-rake gitlab:setup GITLAB_ROOT_PASSWORD="$password" GITLAB_ROOT_EMAIL="$email" < <(echo yes) > /dev/null 2>&1
-                echo "Changed password for user root"
+                GITLAB_ROOT_EMAIL="$email" GITLAB_ROOT_PASSWORD="$password" gitlab-ctl reconfigure
               mode: '000700'
               owner: 'root'
               group: 'root'
             '/root/gitlab_extra_config.sh':
               content: |
                 #!/bin/bash
-                email=$1
-                password=$2
-                [ -z "$email" ] && echo "Invalid email" && exit 1
+                password=$1
                 [ -z "$password" ] && echo "Invalid password" && exit 1
-                # Obtain a token
-                token=$(curl -s -F grant_type=password -F "username=$email" -F "password=$password" -X POST http://localhost:80/oauth/token | jq '.access_token' | tr -d '"')
+                # Obtain a token (https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples#curl-command-password-grant)
+                token=$(curl -s -F grant_type=password -F "username=root" -F "password=$password" -X POST http://localhost:80/oauth/token | jq '.access_token' | tr -d '"')
+                [ "$token" == "null" ] && echo "Failed to retrieve token" && exit 1 
                 url="http://localhost:80/api/v4/application/settings"
                 echo "Changing settings (token=$token)..."
-                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?signup_enabled=false" > /dev/null
-                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?default_project_visibility=public" > /dev/null
-                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?email_author_in_body=true" > /dev/null
-                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?gravatar_enabled=false" > /dev/null
-                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?help_page_hide_commercial_content=true" > /dev/null
-                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?html_emails_enabled=true" > /dev/null
-                curl -s --request PUT  -H "Authorization: Bearer $token" "$url?html_emails_enabled=true" > /dev/null
+                
+                change_settings()
+                {
+                  local key="$1"
+                  local value="$2"
+                  echo $key=$(curl -s --request PUT -H "Authorization: Bearer $token" "$url?$key=$value" | jq ".$key")                  
+                }
+                change_settings signup_enabled                    false
+                change_settings default_project_visibility        public
+                change_settings email_author_in_body              true
+                change_settings gravatar_enabled                  false
+                change_settings help_page_hide_commercial_content true
+                change_settings html_emails_enabled               true
                 curl -s --request POST -H "Authorization: Bearer $token" -F token=$token http://localhost:80/oauth/revoke > /dev/null
+                
+                cp lib/support/init.d/gitlab /etc/init.d/gitlab
               mode: '000700'
               owner: 'root'
               group: 'root'
           commands:
-            '01_gitlab_configure_url':
+            '01_gitlab_configure_url': 
               command: !Sub 'sudo /root/gitlab_configure_url.sh ${LoadBalancerGitlab.DNSName}'
-            '02_gitlab_configure_ldap':
+            '02_gitlab_configure_ldap': 
               command: !Join
                 - ' '
                 - - 'sudo /root/gitlab_configure_ldap.sh'
@@ -367,12 +373,12 @@ Resources:
                   - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-RootDC'
                   - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-ManagerDN'
                   - !Sub '${LDAPManagerPassword}'
-            '03_gitlab_reconfigure':
-              command: 'sudo gitlab-ctl reconfigure'
-            '04_gitlab_change_password':
+            '04_gitlab_change_password': 
               command: !Sub 'sudo /root/gitlab_change_password.sh "${GitlabAdminEmail}" "${GitlabAdminPassword}"'
-            '05_gitlab_extra_config':
-              command: !Sub 'sudo /root/gitlab_extra_config.sh "${GitlabAdminEmail}" "${GitlabAdminPassword}"'
+            '05_gitlab_extra_config': 
+              command: !Sub 'sudo /root/gitlab_extra_config.sh "${GitlabAdminPassword}"'
+            '99_gitlab_restart': 
+              command: 'sudo gitlab-ctl restart'
     Properties: 
       DisableApiTermination: false
       InstanceInitiatedShutdownBehavior: stop
diff --git a/templates/07-sonarqube.yaml b/templates/07-sonarqube.yaml
--- a/templates/07-sonarqube.yaml
+++ b/templates/07-sonarqube.yaml
@@ -15,6 +15,11 @@
 # - Should use NestedStack as described in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html
 # - Should provide alert when the platform is unhealthy
 # - LOOK AT https://docs.sonarqube.org/display/SONAR/Hardware+Recommendations
+# - Configure email for admin user: architectureemergingtechnologies@allfundsbank.com
+# - Configure webhooks for gitlab or jenkins: cf https://redirect.sonarsource.com/doc/webhooks.html
+# - Configure Jenkins CI: sonar.links.ci
+# - Configure Gitlab SCM: sonar.links.scm
+# - Confiure server base URL: sonar.core.serverBaseURL
 #
 ---
 AWSTemplateFormatVersion: "2010-09-09"
@@ -28,6 +33,7 @@ Metadata:
       - ParentVpcStack
       - ParentLDAPStack
       - ParentDBStack
+      - ParentGitlabStack
     - Label: 
         default: 'EC2 Parameters'
       Parameters:
@@ -44,7 +50,10 @@ Metadata:
     - Label:
         default: 'Sonarqube Parameters'
       Parameters:
+      - SonarqubeAdminEmail
       - SonarqubeAdminPassword
+      - JenkinsUsername
+      - JenkinsPassword
 Parameters: 
   ParentVpcStack: 
     Description: "Enter the name of the VPC Stack where Sonarqube will reside"
@@ -61,6 +70,18 @@ Parameters:
     Type: String
     MinLength: 1
     ConstraintDescription: 'must be the name of the DB stack'
+  ParentGitlabStack:
+    Description: 'Enter the name of the Gitlab Stack'
+    Type: String
+    MinLength: 1
+    ConstraintDescription: 'must be the name of the Gitlab stack'
+  KeyName: 
+    Description: "Optional Key Pair to connect through SSH"
+    Type: "AWS::EC2::KeyPair::KeyName"
+  InstanceType:
+    Description: 'The Sonarqube instance type'
+    Type: String
+    Default: 'c4.large'    
   LDAPManagerPassword: 
     Description: 'The LDAP Manager password'
     Type: String
@@ -71,17 +92,25 @@ Parameters:
     Type: String
     NoEcho: true
     MinLength: 3
-  KeyName: 
-    Description: "Optional Key Pair to connect through SSH"
-    Type: "AWS::EC2::KeyPair::KeyName"
-  InstanceType:
-    Description: 'The Sonarqube instance type'
+  SonarqubeAdminEmail: 
+    Description: 'The Sonarqube Admin email'
     Type: String
-    Default: 'c4.large'    
+    Default: 'admin@example.com'
   SonarqubeAdminPassword: 
     Description: 'The Sonarqube Admin password'
     Type: String
     MinLength: 1
+    NoEcho: true
+  JenkinsUsername: 
+    Description: 'The username Jenkins will use to execute analysis'
+    Type: String
+    MinLength: 1
+    Default: 'jenkins'    
+  JenkinsPassword: 
+    Description: 'The password Jenkins will use to execute analysis (default to jenkins)'
+    Type: String
+    MinLength: 1
+    Default: 'jenkins'    
     NoEcho: true
 Conditions:
   HasKeyName: !Not [!Equals [!Ref KeyName, '']]
@@ -288,6 +317,12 @@ Resources:
                 sonar.jdbc.username=sonarqube
                 sonar.jdbc.password=sonarqube
                 sonar.updatecenter.activate=true
+                email.from=noreply@${AWS::StackName}
+                email.smtp_secure_connection.secured=false
+                email.smtp_host.secured=
+                email.smtp_password.secured=
+                email.smtp_username.secured=
+                sonar.links.ci=
                 sonar.forceAuthentication=true
                 sonar.security.realm=LDAP
                 ldap.url=ldap://%ldapHostname%:%ldapPort%
@@ -298,6 +333,10 @@ Resources:
                 ldap.user.request=(&(objectClass=person)(uid={login}))
                 ldap.user.realNameAttribute=displayName
                 ldap.user.emailAttribute=mail
+                sonar.gitlab.url=http://%gitlabDNSName%
+                sonar.gitlab.ignore_certificate=true
+                sonar.gitlab.user_token=%gitlabToken%
+                sonar.gitlab.ping_user=true
               mode: '000600'
               owner: 'sonar'
               group: 'sonar'
@@ -336,6 +375,35 @@ Resources:
                 [ -z "$managerDN" ] && echo "Invalid managerDN" && exit 1
                 [ -z "$managerPassword" ] && echo "Invalid managerPassword" && exit 1
                 sed -ibckp -E "s/%ldapHostname%/$ldapHostname/;s/%ldapPort%/$ldapPort/;s/%rootDC%/$rootDC/;s/%managerDN%/$managerDN/;s/%managerPassword%/$managerPassword/" /opt/sonar/conf/sonar.properties
+              mode: '000700'
+              owner: 'root'
+              group: 'root'
+            '/root/sonarqube_configure_gitlab.sh':
+              content: |
+                #!/bin/bash
+                gitlabDNSName=$1
+                ldapPort=$2
+                rootDC=$3
+                managerDN="$4"
+                managerPassword=$5
+                [ -z "$gitlabDNSName" ] && echo "Invalid gitlabDNSName" && exit 1
+                [ -z "$ldapPort" ] && echo "Invalid ldapPort" && exit 1
+                [ -z "$rootDC" ] && echo "Invalid rootDC" && exit 1
+                [ -z "$managerDN" ] && echo "Invalid managerDN" && exit 1
+                [ -z "$managerPassword" ] && echo "Invalid managerPassword" && exit 1
+                # First create a sonarqube in Gitlab
+                email=$1
+                password=$2
+                [ -z "$email" ] && echo "Invalid email" && exit 1
+                [ -z "$password" ] && echo "Invalid password" && exit 1
+                # Obtain a token
+                token=$(curl -s -F grant_type=password -F "username=$email" -F "password=$password" -X POST http://$gitlabDNSName/oauth/token | jq '.access_token' | tr -d '"')
+                url="http://$gitlabDNSName/api/v4"
+                gitlabPassword=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
+                echo "Creating sonarqube user in Gitlab @ $gitlabDNSName..."
+                userId=$(curl -s --request POST -H "Authorization: Bearer $token" "$url/users" -F "email=sonarqube@example.com" -F "password=$gitlabPassword" -F "username=sonarqube" -F "name=Sonarqube User" -F "admin=true" -F "skip_confirmation=true" | jq '.id')
+                gitlabToken=$(curl -s --request POST -H "Authorization: Bearer $token" "$url/users/$userId/impersonation_tokens" -F "name=SONARQUBE" -F "scopes[]=api" | jq '.id' | tr -d'"')
+                sed -ibckp -E "s/%gitlabDNSName%/$gitlabDNSName/;s/%gitlabToken%/$gitlabToken/" /opt/sonar/conf/sonar.properties
               mode: '000700'
               owner: 'root'
               group: 'root'
@@ -439,16 +507,25 @@ Resources:
                   - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-RootDC'
                   - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-ManagerDN'
                   - !Sub '${LDAPManagerPassword}'
-            '04_sonarqube_start':
+            '04_sonarqube_configure_gitlab':
+              command: !Join
+                - ' '
+                - - 'sudo /root/sonarqube_configure_gitlab.sh'
+                  - 'Fn::ImportValue': !Sub '${ParentGitlabStack}-DNSName'
+                  - 'Fn::ImportValue': !Sub '${ParentGitlabStack}-LDAPPort'
+                  - 'Fn::ImportValue': !Sub '${ParentGitlabStack}-RootDC'
+                  - 'Fn::ImportValue': !Sub '${ParentGitlabStack}-ManagerDN'
+                  - !Sub '${LDAPManagerPassword}'
+            '05_sonarqube_start':
               command: 'sudo service sonar start'
-            '05_sonarqube_change_password':
+            '06_sonarqube_change_password':
               command: !Join
                 - ' '
                 - - 'sudo /root/sonarqube_change_password.sh'
                   - 'Fn::ImportValue': !Sub '${ParentDBStack}-EndpointAddress'
                   - 'Fn::ImportValue': !Sub '${ParentDBStack}-EndpointPort'
                   - !Sub '${SonarqubeAdminPassword}'
-            '06_sonarqube_start':
+            '99_sonarqube_start':
               command: 'sudo service sonar restart'
           services: 
             sysvinit: 
@@ -502,12 +579,18 @@ Resources:
           Value: !Sub '${AWS::StackName}-VolumeData'
 Outputs: 
   InstanceId: 
-    Description: "InstanceId of the newly created Sonarqube instance"
+    Description: 'InstanceId of the newly created Sonarqube instance'
     Value: !Ref SonarqubeHost
     Export:
       Name: !Sub '${AWS::StackName}-InstanceId'
   DNSName: 
-    Description: "Public DNS address of the internet facing ELB"
+    Description: 'Public DNS address of the internet facing ELB'
     Value: !Sub '${LoadBalancerSonarqube.DNSName}'
     Export:
       Name: !Sub '${AWS::StackName}-DNSName'
+  JenkinsUsername:
+    Description: 'The username Jenkins will use to start analysis'
+    Value: !Ref JenkinsUsername
+    Export:
+      Name: !Sub '${AWS::StackName}-JenkinsUsername'
+      
