Make Sonarqube fault tolerant

diff --git a/templates/07-sonarqube.yaml b/templates/07-sonarqube.yaml
--- a/templates/07-sonarqube.yaml
+++ b/templates/07-sonarqube.yaml
@@ -144,15 +144,58 @@ Mappings:
 Conditions:
   HasKeyName: !Not [!Equals [!Ref KeyName, '']]
 Resources: 
-  #
-  # Let's create the SecurityGroup for the ELB LoadBalancer. Basically it should only allow traffic on the HTTP/S port
-  #   from the Internet. If you want to restrict the IP from which to accept traffic, do it here. you can have a look 
-  #   at the 01-vpc.yaml, and more specifically the SecurityGroupDMZ for an example.
-  #
+  TopicHealth: 
+    Type: 'AWS::SNS::Topic'
+    Properties: 
+      DisplayName: !Sub '${AWS::StackName} - Server health notification'
+      Subscription:
+        - Endpoint: !Ref SonarqubeAdminEmail
+          Protocol: 'email'
+  AutoScalingGroup: 
+    Type: 'AWS::AutoScaling::AutoScalingGroup'
+    Properties:
+      HealthCheckGracePeriod: 300
+      HealthCheckType: ELB
+      LaunchConfigurationName: !Ref LaunchConfiguration
+      MinSize: 1
+      MaxSize: 1
+      NotificationConfigurations:
+        - TopicARN: !Ref TopicHealth
+          NotificationTypes:
+            - 'autoscaling:EC2_INSTANCE_LAUNCH'
+            - 'autoscaling:EC2_INSTANCE_LAUNCH_ERROR'
+            - 'autoscaling:EC2_INSTANCE_TERMINATE'
+            - 'autoscaling:EC2_INSTANCE_TERMINATE_ERROR'
+      TargetGroupARNs:
+        - !Ref TargetGroup
+      VPCZoneIdentifier: 
+        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPrivateAZA'
+        - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPrivateAZB'
+      Tags: 
+        - Key: PLATFORM
+          Value: 
+            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
+          PropagateAtLaunch: true
+        - Key: Name
+          Value: !Sub '${AWS::StackName}-AutoScalingGroup'
+          PropagateAtLaunch: true
+    CreationPolicy: 
+      ResourceSignal: 
+        Timeout: PT15M
+        Count: 1
+    UpdatePolicy: 
+      AutoScalingRollingUpdate: 
+        MinInstancesInService: 1
+        MaxBatchSize: 1
+        PauseTime: PT15M
+        WaitOnResourceSignals: true
+    DependsOn:
+      - MountTargetA
+      - MountTargetB
   SecurityGroupELB:
     Type: 'AWS::EC2::SecurityGroup'
     Properties:
-      GroupDescription: 'Security Group to access Sonarqube ELB'
+      GroupDescription: 'Security Group to access the LoadBalancer'
       VpcId:
         'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc'
       SecurityGroupIngress:
@@ -170,10 +213,10 @@ Resources:
             'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
         - Key: Name
           Value: !Sub '${AWS::StackName}-SecurityGroupELB'
-  LoadBalancerSonarqube:
+  LoadBalancer:
     Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
     Properties:
-      Scheme: 'internet-facing'
+      Scheme: internet-facing
       SecurityGroups:
       - !Ref SecurityGroupELB
       Subnets: 
@@ -184,8 +227,8 @@ Resources:
           Value: 
             'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
         - Key: Name
-          Value: !Sub '${AWS::StackName}-LoadBalancerSonarqube'
-  TargetGroupSonarqube:
+          Value: !Sub '${AWS::StackName}-LoadBalancer'
+  TargetGroup:
     Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
     Properties:
       HealthCheckIntervalSeconds: 10
@@ -202,22 +245,19 @@ Resources:
           Value: 
             'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
         - Key: Name
-          Value: !Sub '${AWS::StackName}-TargetGroupSonarqube'
+          Value: !Sub '${AWS::StackName}-TargetGroup'
       VpcId:
         'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc'
       TargetGroupAttributes:
         - Key: 'deregistration_delay.timeout_seconds'
           Value: 30
-      Targets:
-        - Id: !Ref SonarqubeHost
-    DependsOn: SonarqubeHost
-  ListenerSonarqube:
+  Listener:
     Type: 'AWS::ElasticLoadBalancingV2::Listener'
     Properties:
       DefaultActions:
-      - TargetGroupArn: !Ref TargetGroupSonarqube
+      - TargetGroupArn: !Ref TargetGroup
         Type: forward
-      LoadBalancerArn: !Ref LoadBalancerSonarqube
+      LoadBalancerArn: !Ref LoadBalancer
       Port: 80
       Protocol: HTTP
   SecurityGroupEFS:
@@ -265,41 +305,10 @@ Resources:
         - !Ref SecurityGroupEFS
       SubnetId: 
         'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPrivateAZB'
-  #
-  # Let's create the Sonarqube instance.
-  # 
-  # TODO: Should have a specific SecurityGroup for the instance in order to only allow traffic on port 8000 (default
-  #   Sonarqube port). Further more I should enable SSL traffic, but beware that the load balancer might not allow 
-  #   communications with a host presenting a self-signed certificate.
-  #
-  SecurityGroupSonarqube:
-    Type: 'AWS::EC2::SecurityGroup'
-    Properties:
-      GroupDescription: 'Security Group to access the Sonarqube instance'
-      VpcId:
-        'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc'
-      SecurityGroupIngress:
-      - SourceSecurityGroupId: 
-          !Ref 'SecurityGroupELB'
-        FromPort: 9000
-        ToPort: 9000
-        IpProtocol: tcp
-      Tags: 
-        - Key: PLATFORM
-          Value: 
-            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
-        - Key: Name
-          Value: !Sub '${AWS::StackName}-SecurityGroupSonarqube'
-  #
-  # Ok let's configure the main host then
-  #
-  SonarqubeHost: 
-    Type: 'AWS::EC2::Instance'
+  LaunchConfiguration:
+    Type: 'AWS::AutoScaling::LaunchConfiguration'
     Metadata:
       AWS::CloudFormation::Init:
-        #
-        # The logs for the cfn-init command are available in the instance in /var/log/cfn-init-cmd.log 
-        # , InstallSonarqube
         configSets: 
           default: [ Bootstrap, BootstrapApplication, InstallApplication ]
         Bootstrap:
@@ -377,6 +386,7 @@ Resources:
         BootstrapApplication:
           packages:
             yum: 
+              jq: []
               mysql56: []
               py-bcrypt: []
               java-1.8.0-openjdk: []
@@ -388,7 +398,7 @@ Resources:
               owner: "root"
               group: "root"
             '/root/create_fs.sh': 
-              content: |
+              content: !Sub |
                 #!/bin/bash -x
                 MNT=/mnt/sonar
                 [ ! -d $MNT ] && mkdir $MNT
@@ -410,12 +420,11 @@ Resources:
         InstallApplication: 
           packages:
             yum:
-              jq: []
               sonar: []
           files:
             '/opt/sonar/conf/sonar.properties': 
               content: !Sub |
-                sonar.jdbc.url=jdbc:mysql://%address%:%port%/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
+                sonar.jdbc.url=jdbc:mysql://%endpointAddress%:%endpointPort%/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
                 sonar.jdbc.username=sonarqube
                 sonar.jdbc.password=sonarqube
                 sonar.updatecenter.activate=true
@@ -445,32 +454,30 @@ Resources:
             '/root/sonarqube_create_db.sh':
               content: |
                 #!/bin/bash
-                address=$1
-                port=$2
-                username=$3
-                password=$4
-                [ -z "$address" ] && echo "Invalid address" && exit 1
-                [ -z "$port" ] && echo "Invalid port" && exit 1
-                [ -z "$username" ] && echo "Invalid username" && exit 1
-                [ -z "$password" ] && echo "Invalid password" && exit 1
-                mysql -h $address -P $port --user=$username --password=$password <<EOF
-                DROP DATABASE IF EXISTS sonarqube;
+                endpointAddress=$1
+                endpointPort=$2
+                masterUsername=$3
+                masterUserPassword=$4
+                [ -z "$endpointAddress" ] && echo "Invalid endpointAddress" && exit 1
+                [ -z "$endpointPort" ] && echo "Invalid endpointPort" && exit 1
+                [ -z "$masterUsername" ] && echo "Invalid masterUsername" && exit 1
+                [ -z "$masterUserPassword" ] && echo "Invalid masterUserPassword" && exit 1
+                mysql -h $endpointAddress -P $endpointPort --user=$masterUsername --password=$masterUserPassword <<EOF
                 CREATE DATABASE sonarqube CHARACTER SET utf8 COLLATE utf8_bin;
                 GRANT ALL on sonarqube.* TO 'sonarqube'@'%' IDENTIFIED BY 'sonarqube';
                 FLUSH PRIVILEGES;
                 EOF
-                touch /mnt/sonar/opt/.db_created
               mode: '000700'
               owner: 'root'
               group: 'root'
             '/root/sonarqube_configure_db.sh':
               content: |
                 #!/bin/bash
-                address=$1
-                port=$2
-                [ -z "$address" ] && echo "Invalid address" && exit 1
-                [ -z "$port" ] && echo "Invalid port" && exit 1
-                sed -ibckp -E "s/%address%/$address/;s/%port%/$port/" /opt/sonar/conf/sonar.properties
+                endpointAddress=$1
+                endpointPort=$2
+                [ -z "$endpointAddress" ] && echo "Invalid endpointAddress" && exit 1
+                [ -z "$endpointPort" ] && echo "Invalid endpointPort" && exit 1
+                sed -ibckp -E "s/%endpointAddress%/$endpointAddress/;s/%endpointPort%/$endpointPort/" /opt/sonar/conf/sonar.properties
               mode: '000700'
               owner: 'root'
               group: 'root'
@@ -493,7 +500,7 @@ Resources:
               group: 'root'
             '/root/sonarqube_configure_gitlab.sh':
               content: |
-                #!/bin/bash -x
+                #!/bin/bash
                 gitlabDNSName=$1
                 gitlabRootPassword=$2
                 sonarqubeAdminEmail=$3
@@ -607,20 +614,18 @@ Resources:
                   - 'Fn::ImportValue': !Sub '${ParentDBStack}-EndpointPort'
                   - 'Fn::ImportValue': !Sub '${ParentDBStack}-MasterUsername'
                   - !Sub '${DBMasterUserPassword}'
-              test: 'test ! -f /mnt/sonar/.db_created'
+              test: 'sudo test ! -e /mnt/sonar/.application_configured'
             '03_sonarqube_configure_db':
               command: !Join
                 - ' '
                 - - 'sudo /root/sonarqube_configure_db.sh'
                   - 'Fn::ImportValue': !Sub '${ParentDBStack}-EndpointAddress'
                   - 'Fn::ImportValue': !Sub '${ParentDBStack}-EndpointPort'
-                  - 'Fn::ImportValue': !Sub '${ParentDBStack}-MasterUsername'
-                  - !Sub '${DBMasterUserPassword}'
             '04_sonarqube_configure_ldap':
               command: !Join
                 - ' '
                 - - 'sudo /root/sonarqube_configure_ldap.sh'
-                  - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-LDAPHostname'
+                  - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-DNSName'
                   - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-LDAPPort'
                   - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-RootDC'
                   - 'Fn::ImportValue': !Sub '${ParentLDAPStack}-ManagerDN'
@@ -632,6 +637,8 @@ Resources:
                   - 'Fn::ImportValue': !Sub '${ParentGitlabStack}-DNSName'
                   - !Sub '${GitlabRootPassword}'
                   - !Sub '${SonarqubeAdminEmail}'
+              test: 'sudo test ! -e /mnt/sonar/.application_configured'
+              ignoreErrors: true
             '06_sonarqube_start':
               command: 'sudo service sonar start'
             '07_sonarqube_change_password':
@@ -641,6 +648,9 @@ Resources:
                   - 'Fn::ImportValue': !Sub '${ParentDBStack}-EndpointAddress'
                   - 'Fn::ImportValue': !Sub '${ParentDBStack}-EndpointPort'
                   - !Sub '${SonarqubeAdminPassword}'
+              test: 'sudo test ! -e /mnt/sonar/.application_configured'
+            '98_application_configured':
+              command: 'sudo touch /mnt/sonar/.application_configured'
             '99_sonarqube_start':
               command: 'sudo service sonar restart'
           services: 
@@ -648,23 +658,17 @@ Resources:
               sonar: 
                 enabled: true
                 ensureRunning: true
+                files:
+                  - /opt/sonar/conf/sonar.properties
     Properties: 
-      DisableApiTermination: false
-      InstanceInitiatedShutdownBehavior: stop
       IamInstanceProfile: 
         'Fn::ImportValue': !Sub '${ParentVpcStack}-InstanceProfileTagEC2Instance'      
       ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
       InstanceType: !Ref InstanceType
       KeyName: !If [HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
-      SecurityGroupIds: 
+      SecurityGroups: 
         - 'Fn::ImportValue': !Sub '${ParentVpcStack}-SecurityGroupPrivate'
-        - !Ref SecurityGroupSonarqube
-      SubnetId: 
-        'Fn::ImportValue': !Sub '${ParentVpcStack}-SubnetPrivateAZA'
-      Volumes: 
-        - VolumeId: !Ref VolumeData
-          Device: '/dev/xvdb'
-      Monitoring: false
+        - !Ref SecurityGroupHealthCheck
       UserData:
         'Fn::Base64': !Sub |
           #!/bin/bash
@@ -673,35 +677,29 @@ Resources:
           yum install -y aws-cfn-bootstrap
           /opt/aws/bin/cfn-init --verbose --region ${AWS::Region} --stack ${AWS::StackName} --resource LaunchConfiguration
           /opt/aws/bin/cfn-signal -e $?   --region ${AWS::Region} --stack ${AWS::StackName} --resource AutoScalingGroup
-      Tags: 
-        - Key: PLATFORM
-          Value: 
-            'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
-        - Key: Name
-          Value: !Sub '${AWS::StackName}-SonarqubeHost'
-    DependsOn: VolumeData
-  VolumeData:
-    Type: 'AWS::EC2::Volume'
+  SecurityGroupHealthCheck:
+    Type: 'AWS::EC2::SecurityGroup'
     Properties:
-      Size: 500
-      Encrypted: true
-      VolumeType: gp2
-      AvailabilityZone: 
-        'Fn::ImportValue': !Sub '${ParentVpcStack}-AvailabilityZoneSubnetPrivateAZA'
+      GroupDescription: 'Security Group for the Health Check'
+      VpcId: 
+        'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc'
+      SecurityGroupIngress:
+      - CidrIp: '10.0.0.0/16'
+#          Fn::GetAtt: [ 'Fn::ImportValue': !Sub '${ParentVpcStack}-Vpc', CidrBlock ]
+        FromPort: 9000
+        ToPort: 9000
+        IpProtocol: tcp
       Tags: 
         - Key: PLATFORM
           Value: 
             'Fn::ImportValue': !Sub '${ParentVpcStack}-StackName'
         - Key: Name
-          Value: !Sub '${AWS::StackName}-VolumeData'
+          Value: !Sub '${AWS::StackName}-SecurityGroupHealthCheck'
+
 Outputs: 
-  InstanceId: 
-    Description: 'InstanceId of the newly created Sonarqube instance'
-    Value: !Ref SonarqubeHost
-    Export:
-      Name: !Sub '${AWS::StackName}-InstanceId'
   DNSName: 
     Description: 'Public DNS address of the internet facing ELB'
-    Value: !Sub '${LoadBalancerSonarqube.DNSName}'
+    Value: !Sub '${LoadBalancer.DNSName}'
     Export:
       Name: !Sub '${AWS::StackName}-DNSName'
+      
